# Generated by Django 5.2.5 on 2025-11-11 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='status',
            new_name='is_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_recurring_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='task.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='parent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='task.task'),
        ),
    ]
