# Generated by Django 5.2.5 on 2025-11-11 04:36

from django.db import migrations, models


def populate_badges(apps, schema_editor):
    Badges = apps.get_model('user', 'Badges')
    
    badges_data = [
        {'name': 'beginner', 'karma_min': 0, 'karma_max': 499},
        {'name': 'novice', 'karma_min': 500, 'karma_max': 2499},
        {'name': 'intermediate', 'karma_min': 2500, 'karma_max': 4999},
        {'name': 'professional', 'karma_min': 5000, 'karma_max': 7499},
        {'name': 'expert', 'karma_min': 7500, 'karma_max': 9999},
        {'name': 'master', 'karma_min': 10000, 'karma_max': 19999},
        {'name': 'grand_master', 'karma_min': 20000, 'karma_max': 49999},
        {'name': 'enlightened', 'karma_min': 50000, 'karma_max': 999999},
    ]
    
    for badge_data in badges_data:
        Badges.objects.get_or_create(
            name=badge_data['name'],
            defaults={
                'karma_min': badge_data['karma_min'],
                'karma_max': badge_data['karma_max']
            }
        )


def reverse_populate_badges(apps, schema_editor):
    Badges = apps.get_model('user', 'Badges')
    Badges.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_badges_myuser_current_streak_myuser_highest_streak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badges',
            name='karma_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='badges',
            name='karma_max',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(populate_badges, reverse_populate_badges),
    ]

